import type {Metadata} from "next";
import localFont from "next/font/local";
import "./globals.css";
import "normalize.css";
import Navbar from "@/components/Navbar";
import Sidebar from "@/components/sidebar/Sidebar";
import {getMenuHeader} from "@/services/apis/config.service";
import ExpandSidebar from "@/components/sidebar/ExpandSidebar";
import MyHoverCard from "./components/MyHoverCard";
import {getSearch} from "@/services/apis/search.service";
import {getProduct} from "@/services/apis/payment.service";
import React from "react";
import Splash from "@/components/Splash";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
                                             children,
                                         }: Readonly<{
    children: React.ReactNode;
}>) {
    const menu = await getMenuHeader();
    const search: any = await getSearch()
    const product: any = await getProduct();

    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <header>
            <Navbar search={search} product={product}/>
        </header>
        <div className="flex">
            <nav>
                <ExpandSidebar menuHeaderItems={menu?.menu}/>
            </nav>
            <nav>
                <Sidebar menuHeaderItems={menu?.menu}/>
            </nav>
            <div className="w-full">{children}</div>
        </div>
        <Splash/>
        <MyHoverCard/>

        </body>
        </html>
    );
}
